### ISSUE TITLE
Support for DSC Panels

### ISSUE THREAD

**Issue by dustindclark** [mklips0/homebridge-envisakit#2]
Would really like to see support for DSC panels.  If I get a chance, I will try to contribute...but I won't have any way to regression test Honeywell panels.

**Comment by dustindclark** [comment]
@mklips0 , started looking at this last night.  Just out of curiosity, what was the reason for using a CLI instead of initiating the TCP socket connection directly from the Node server?

**Comment by mklips0** [comment]
Yeah, I admit it's not super elegant. It's just due to the fact that I use the envisakit script for other things apart from homebridge, so it was less effort for me to write a reusable script in python that does the heavy lifting, and then call that script from homebridge as needed. If you only care about homebridge support, it would be more elegant to just write the envisalink communication directly into a homebridge plugin.

**Comment by dustindclark** [comment]
Gotcha.  Just making sure that I wasn't missing something.  I'll take a
stab at opening the sockets directly from Node.  Thanks.

Dustin

Sent from my iPhone

On Jan 13, 2016, at 1:44 PM, C. M. <notifications@github.com> wrote:

Yeah, I admit it's not super elegant. It's just due to the fact that I use
the envisakit script for other things apart from homebridge, so it was less
effort for me to write a reusable script in python that does the heavy
lifting, and then call that script from homebridge as needed. If you only
care about homebridge support, it would be more elegant to just write the
envisalink communication directly into a homebridge plugin.

—
Reply to this email directly or view it on GitHub
<https://github.com/mklips0/homebridge-envisakit/issues/2#issuecomment-171410835>
.
